# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PictureGenerator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PictureGenerator
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.5'

  target 'PictureGeneratorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PictureGeneratorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
